server:
  port: 8002

libra:
  log:
    kafka: false
    trace: false
    level: error,info

jwt:
  secret: abcdefg
  expiration: 604800

spring:
  application:
    name: libra-poetry
  datasource:
    url: jdbc:mysql://localhost:3306/libra_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: BATCH
    producer:
      batchSize: 500
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: com.libra.core.logger.serizlizer.FastjsonKafkaSerializer
    consumer:
      group-id: commonLogList
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: com.libra.core.logger.serizlizer.FastjsonKafkaDeserializer
      auto-offset-reset: earliest
      maxPollRecords: 500

mybatis-plus:
  typeAliasesPackage: com.libra.cloud.poetry.entity;com.libra.cloud.system.entity